# Generated by Django 6.0.7 on 2026-08-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='source',
            field=models.CharField(choices=[('dou', 'DOU'), ('djinni', 'Djinni'), ('jobicy', 'Jobicy')], max_length=20),
        ),
    ]
