# Generated by Django 6.0.7 on 2026-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='language',
            field=models.CharField(default='uk', max_length=5),
        ),
    ]
